spring:
  application:
    name: ms-inventario
  datasource:
    url: jdbc:mysql://localhost:3306/db_inventario
    username: root
    password: Contrasena123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30